### ISSUE TITLE
Make it possible to instantiate a client without the neo connection process starting automatically

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/swarm#189]
It's not always desired that the client start the connection process automatically as soon as it's constructed. It's a reasonable default behaviour, and is convenient for simple usage (i.e. not having to explicitly do anything to connect), but should be configurable.

**Comment by gavin-norman-sociomantic** [comment]
Suggestion:
1. Add a config option to disable automatic connection.
2. Add a `connect()` method to the neo client.

**Comment by gavin-norman-sociomantic** [comment]
>Add a config option to disable automatic connection.

One problem here: this isn't a configuration issue; it's a coding issue. Either the code is written to expect automatic connection or manual connection. Configuring at runtime doesn't make sense.

_Maybe_ we need to move toward a `Settings` struct, which could contain the connection notifier as well.

**Comment by joseph-wakeling-sociomantic** [comment]
Note that this has some key relevance w.r.t. the changes introduced in https://github.com/sociomantic-tsunami/ocean/pull/375.

It's common practice to initialize the various `IClient` implementations used by an app inside the app-class `run` method.  In traditional usage this would mean they are initialized before the epoll eventloop starts.  However, with the changes introduced in the above PR, common practice will be for the eventloop to start _before_ the `run` method is launched (since will now be run inside a scheduled task).

This means that whereas previously there was a clean separation between instantiating the client instance, and beginning to connect (which only starts after the epoll eventloop is initialized), the user no longer has control in this respect.
