### ISSUE TITLE
Make usage of logrotate optional

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/swarm#221]
I have discovered that some of our internal projects maintain fully copy of some of swarm stats modules because they don't use logrotate. This is obviously very inefficient and suitable swarm side solution should be implemented.

**Comment by mathias-lang-sociomantic** [comment]
The reason not to use logrotate though was that logrotate sends a signal when a single file is rotated. If you have many log files, and one with a high write rate, you'll end up reloading very often *all* the files instead of just one, which is what caused the process to hang.

Now that https://github.com/sociomantic-tsunami/ocean/issues/190 is implemented, it might not be an issue anymore (but of course it'll need to be benchmarked).

**Comment by gavin-norman-sociomantic** [comment]
Yeah, the problem is not in swarm, it's in the app. Updating it to use https://github.com/sociomantic-tsunami/ocean/issues/190 should fix the problem and remove the need for keeping old copies of stats logging modules from ocean/swarm.
